#!/usr/bin/env python

from argparse import ArgumentParser, FileType
from gzip import compress
from sys import stdin, stdout


def main():
    arg_parser = ArgumentParser()
    arg_parser.add_argument('file', nargs='?', type=FileType('rb'), default=stdin.buffer)
    args = arg_parser.parse_args()
    out = compress(args.file.read())
    stdout.buffer.write(out)


if __name__ == "__main__":
    main()
